project_id = "fxpkhwazdiscoesaiskh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.suggest]
verify_jwt = false
