// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-analyses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-analyses.ts
var list_analyses_default = defineTool({
  name: "list_analyses",
  title: "List code analyses",
  description: "List the signed-in user's saved code analyses, newest first, with summary metrics (project name, language, completion, confidence).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many analyses to return."),
    language: z.string().trim().min(1).optional().describe("Filter by detected language, e.g. TypeScript.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, language }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("analyses").select(
      "id, project_name, language, goal, source, completion_percentage, effort_level, confidence_score, total_files, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (language) query = query.ilike("language", language);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { analyses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-analysis.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_analysis_default = defineTool2({
  name: "get_analysis",
  title: "Get analysis details",
  description: "Fetch one saved analysis by id, including next steps, risks, issues, security issues, dependency audit and compliance checks.",
  inputSchema: {
    id: z2.string().uuid().describe("The analysis id returned by list_analyses."),
    include_code: z2.boolean().default(false).describe("Include the analyzed source snapshot (can be very large).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, include_code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const columns = "id, project_name, language, goal, source, current_state, completion_percentage, effort_level, confidence_score, next_steps, risks, issues, architectural_improvements, security_issues, dependency_audit, compliance_checks, total_files, total_size_bytes, created_at" + (include_code ? ", code" : "");
    const { data, error } = await supabase.from("analyses").select(columns).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No analysis found with that id." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { analysis: data }
    };
  }
});

// src/lib/mcp/tools/search-analyses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_analyses_default = defineTool3({
  name: "search_analyses",
  title: "Search analyses",
  description: "Search the signed-in user's analyses by project name, goal or current state text.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Text to search for."),
    limit: z3.number().int().min(1).max(50).default(10).describe("Maximum results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("analyses").select("id, project_name, language, goal, current_state, completion_percentage, created_at").or(
      `project_name.ilike.%${escaped}%,goal.ilike.%${escaped}%,current_state.ilike.%${escaped}%`
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-security-report.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_security_report_default = defineTool4({
  name: "get_security_report",
  title: "Get security report",
  description: "Aggregate security issues, dependency audit findings and compliance checks across the signed-in user's recent analyses.",
  inputSchema: {
    analysis_id: z4.string().uuid().optional().describe("Limit the report to one analysis. Omit to aggregate recent analyses."),
    limit: z4.number().int().min(1).max(25).default(5).describe("How many recent analyses to aggregate when analysis_id is omitted.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ analysis_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("analyses").select("id, project_name, language, security_issues, dependency_audit, compliance_checks, created_at").order("created_at", { ascending: false });
    query = analysis_id ? query.eq("id", analysis_id) : query.limit(limit ?? 5);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const count = (value) => Array.isArray(value) ? value.length : 0;
    const report = {
      analyses: rows,
      totals: {
        security_issues: rows.reduce((sum, r) => sum + count(r.security_issues), 0),
        dependency_findings: rows.reduce((sum, r) => sum + count(r.dependency_audit), 0),
        compliance_checks: rows.reduce((sum, r) => sum + count(r.compliance_checks), 0)
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(report, null, 2) }],
      structuredContent: report
    };
  }
});

// src/lib/mcp/tools/delete-analysis.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var delete_analysis_default = defineTool5({
  name: "delete_analysis",
  title: "Delete analysis",
  description: "Permanently delete one of the signed-in user's saved analyses by id.",
  inputSchema: { id: z5.string().uuid().describe("The analysis id to delete.") },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("analyses").delete().eq("id", id).select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: "No analysis was deleted (not found)." }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Deleted analysis ${id}.` }],
      structuredContent: { deleted_id: id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fxpkhwazdiscoesaiskh";
var mcp_default = defineMcp({
  name: "code-context-guardian",
  title: "Code Context Guardian",
  version: "0.1.0",
  instructions: "Tools for DevResume AI / Code Context Guardian. Use `list_analyses` or `search_analyses` to find the signed-in user's saved code analyses, `get_analysis` for full details of one, `get_security_report` for aggregated security, dependency and compliance findings, and `delete_analysis` to remove one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_analyses_default,
    get_analysis_default,
    search_analyses_default,
    get_security_report_default,
    delete_analysis_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
